# Generated by Django 5.1.3 on 2025-07-15 12:58

import apps.narrativa.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo_Narrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Narrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Narrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('foto', models.ImageField(blank=True, default='narrativas/default/default.png', null=True, upload_to=apps.narrativa.models.atualizar_nome_foto, verbose_name='Foto')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor(es)')),
                ('anexo', models.FileField(blank=True, null=True, upload_to=apps.narrativa.models.atualizar_nome_anexo, verbose_name='Anexo')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('slug', models.CharField(max_length=15, unique=True)),
                ('estilo_narrativa', models.ManyToManyField(to='narrativa.estilo_narrativa')),
                ('tipo_narrativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='narrativa.tipo_narrativa')),
            ],
        ),
    ]
