# Generated by Django 5.1.7 on 2025-05-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrativa',
            name='tipo_narrativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='narrativa.tipo_narrativa'),
        ),
    ]
