# Generated by Django 5.1.7 on 2025-07-22 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narrativa', '0002_alter_narrativa_tipo_narrativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrativa',
            name='tipo_narrativa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='narrativa.tipo_narrativa'),
            preserve_default=False,
        ),
    ]
