# Generated by Django 5.1.3 on 2025-07-15 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('narrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local_Narrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo_Narrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Publico_Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Turno_Narrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores_Narrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_personagens_reais', models.IntegerField(verbose_name='Quantidade de Personagens Reais')),
                ('qtd_personagens_imaginarios', models.IntegerField(verbose_name='Quantidade de Personagens Imaginarios')),
                ('qtd_personagens_criancas', models.IntegerField(verbose_name='Quantidade de Personagens Crianças')),
                ('qtd_personagens_adultos', models.IntegerField(verbose_name='Quantidade de Personagens Adultos')),
                ('qtd_personagens_idosos', models.IntegerField(verbose_name='Quantidade de Personagens Idosos')),
                ('qtd_personagens_animais', models.IntegerField(verbose_name='Quantidade de Personagens Animais')),
                ('narrativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='narrativa.narrativa')),
                ('locais', models.ManyToManyField(to='indicador.local_narrativa')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.periodo_narrativa')),
                ('publicos', models.ManyToManyField(to='indicador.publico_destino')),
                ('turnos', models.ManyToManyField(to='indicador.turno_narrativa')),
            ],
        ),
    ]
